import { createClient } from '@libsql/client';
import { drizzle } from 'drizzle-orm/libsql';
import * as schema from './schema';

export const client = createClient({
  url: process.env.TURSO_DATABASE_URL || 'file:local.db',
  authToken: process.env.TURSO_AUTH_TOKEN,
});

export const db = drizzle(client, { schema });

export async function initDB() {
  console.log('Initializing Database...');

  // Create tables using raw SQL that matches Drizzle schema
  // We can use drizzle's migrate but for simplicity/learning we keep raw queries or check existence
  // Note: better-auth usually expects timestamps as Dates but we store them as timestamps in sqlite
  // Drizzle schema uses { mode: 'timestamp' } which means it's stored as INTEGER (milliseconds or seconds depend on config, default JS Date is ms)
  // But SQLITE usually stores Date as String or Integer.
  // Better Auth default sqlite schema (generated by CLI) uses timestamps.

  await client.execute(`
    CREATE TABLE IF NOT EXISTS user (
      id TEXT PRIMARY KEY,
      name TEXT NOT NULL,
      email TEXT NOT NULL UNIQUE,
      emailVerified INTEGER,
      image TEXT,
      createdAt INTEGER NOT NULL,
      updatedAt INTEGER NOT NULL
    );
  `);

  await client.execute(`
    CREATE TABLE IF NOT EXISTS session (
      id TEXT PRIMARY KEY,
      userId TEXT NOT NULL,
      token TEXT UNIQUE NOT NULL,
      expiresAt INTEGER NOT NULL,
      ipAddress TEXT,
      userAgent TEXT,
      createdAt INTEGER NOT NULL,
      updatedAt INTEGER NOT NULL, -- Fixed missing comma from previous raw SQL if any
      FOREIGN KEY(userId) REFERENCES user(id) ON DELETE CASCADE
    );
  `);

  await client.execute(`
    CREATE TABLE IF NOT EXISTS account (
      id TEXT PRIMARY KEY,
      userId TEXT NOT NULL,
      accountId TEXT NOT NULL,
      providerId TEXT NOT NULL,
      accessToken TEXT,
      refreshToken TEXT,
      accessTokenExpiresAt INTEGER,
      refreshTokenExpiresAt INTEGER,
      scope TEXT,
      idToken TEXT,
      password TEXT,
      createdAt INTEGER NOT NULL,
      updatedAt INTEGER NOT NULL,
      FOREIGN KEY(userId) REFERENCES user(id) ON DELETE CASCADE
    );
  `);

  await client.execute(`
    CREATE TABLE IF NOT EXISTS verification (
      id TEXT PRIMARY KEY,
      identifier TEXT NOT NULL,
      value TEXT NOT NULL,
      expiresAt INTEGER NOT NULL,
      createdAt INTEGER,
      updatedAt INTEGER
    );
  `);

  await client.execute(`
    CREATE TABLE IF NOT EXISTS notes (
      id TEXT PRIMARY KEY,
      user_id TEXT NOT NULL, -- Matching schema user_id
      title TEXT,
      content TEXT NOT NULL,
      is_public INTEGER DEFAULT 0,
      created_at INTEGER NOT NULL, -- mode: number
      updated_at INTEGER NOT NULL, -- mode: number
      FOREIGN KEY(user_id) REFERENCES user(id) ON DELETE CASCADE
    );
  `);

  await client.execute(
    'CREATE INDEX IF NOT EXISTS idx_notes_user ON notes(user_id);',
  );

  console.log('Database initialized (Async Drizzle/Turso)');
}
